# Generated by Django 3.1 on 2020-09-16 01:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LineUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LineUp_Brand', models.CharField(max_length=255)),
                ('LineUp_Model_Code', models.CharField(max_length=255)),
                ('LineUp_Width', models.IntegerField()),
                ('LineUp_Length', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ShoesData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Model_name', models.CharField(max_length=255)),
                ('Model_code', models.CharField(max_length=255)),
                ('Model_lineUp', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Line_Up_models', to='sizoo_proApp.lineup')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserInfo_Gender', models.IntegerField()),
                ('UserInfo_Email', models.CharField(max_length=255)),
                ('UserInfo_User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='UserInfo_User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShoesExp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ShoesExp_Size', models.IntegerField()),
                ('shoesExp_shoe', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='exps', to='sizoo_proApp.shoesdata')),
                ('shoesExp_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_shoes', to='sizoo_proApp.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.IntegerField()),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usedUser', to='sizoo_proApp.userinfo')),
                ('tgtShoe', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tgts', to='sizoo_proApp.shoesdata')),
            ],
        ),
    ]
