# Generated by Django 3.1.1 on 2020-09-15 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LineUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LineUp_Brand', models.CharField(max_length=255)),
                ('LineUp_Model_Num', models.CharField(max_length=255)),
                ('LineUp_Width', models.IntegerField()),
                ('LineUp_Length', models.IntegerField()),
                ('LineUp_Toehil', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserInfo_Gender', models.IntegerField()),
                ('UserInfo_Email', models.CharField(max_length=255)),
                ('UserInfo_User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='UserInfo_User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShoesExp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ShoesExp_Brand', models.CharField(max_length=255)),
                ('ShoesExp_Model_Num', models.CharField(max_length=255)),
                ('ShoesExp_Size', models.IntegerField()),
                ('ShoesExp_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ShoesExp_ID', to='sizoo_proApp.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='ShoesData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ShoesData_Brand', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ShoesData_Brand', to='sizoo_proApp.shoesexp')),
                ('ShoesData_Gender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ShoesData_Gender', to='sizoo_proApp.userinfo')),
                ('ShoesData_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ShoesData_ID', to='sizoo_proApp.userinfo')),
                ('ShoesData_Length', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ShoesData_Length', to='sizoo_proApp.lineup')),
                ('ShoesData_Model_Num', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ShoesData_Model_Num', to='sizoo_proApp.shoesexp')),
                ('ShoesData_Size', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ShoesData_Size', to='sizoo_proApp.shoesexp')),
                ('ShoesData_Toehil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ShoesData_Toehil', to='sizoo_proApp.lineup')),
                ('ShoesData_Width', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ShoesData_Width', to='sizoo_proApp.lineup')),
            ],
        ),
    ]
