# Generated by Django 3.1.1 on 2020-09-21 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sizoo_proApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoesexp',
            name='ShoesExp_vuser',
            field=models.IntegerField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shoesdata',
            name='Model_code',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='shoesexp',
            name='ShoesExp_User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_shoes', to='sizoo_proApp.userinfo'),
        ),
    ]
