# Generated by Django 3.1.1 on 2020-09-21 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sizoo_proApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoesexp',
            name='ShoesExp_vuser',
            field=models.IntegerField(null=True),
        ),
    ]
